CREATE TABLE Books (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Author NVARCHAR(150) NOT NULL,
    Description NVARCHAR(MAX) NULL,
    Available BIT NOT NULL,
    CreationTime DATETIME2 NOT NULL,
    OwnerId UNIQUEIDENTIFIER NOT NULL,
    BorrowerId UNIQUEIDENTIFIER NULL,
    CONSTRAINT FK_Books_Owner FOREIGN KEY (OwnerId) REFERENCES Users(Id),
    CONSTRAINT FK_Books_Borrower FOREIGN KEY (BorrowerId) REFERENCES Users(Id)
);