<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BookShareHub.Application\BookShareHub.Application.csproj" />
    <ProjectReference Include="..\BookShareHub.Domain\BookShareHub.Domain.csproj" />
  </ItemGroup>

</Project>
